Repository griptape-ai/griptape, pull requests merged in 2025-02, with the labels that each got.

#1652 improvements to data sources coverage in cloud docs
  docs/griptape-cloud/data-sources/create-data-source.md
  docs/griptape-cloud/data-sources/getting-started-with-data-sources.md
  docs/griptape-cloud/data-sources/what-are-data-sources.md
  docs/griptape-cloud/index.md
  mkdocs.yml
Labels: type:documentation

#1656 improvements to cloud docs related to Structures
  docs/griptape-cloud/structures/create-structure.md
  docs/griptape-cloud/structures/getting-started-with-structures.md
  docs/griptape-cloud/structures/run-structure.md
  docs/griptape-cloud/structures/what-are-structures.md
  mkdocs.yml
Labels: type:documentation

#1667 docs: enhancements to cloud docs related to knowledge bases
  docs/griptape-cloud/knowledge-bases/getting-started-with-knowledge-bases.md
  docs/griptape-cloud/knowledge-bases/what-are-knowledge-bases.md
  docs/griptape-cloud/structures/what-are-structures.md
  mkdocs.yml
Labels: type:documentation

#1736 update rag engines docs and example to show local rerank driver usage.
  docs/griptape-framework/engines/rag-engines.md
  docs/griptape-framework/engines/src/rag_engines_1.py
Labels: docs

#1743 feat(tools): allow setting allowlist and denylist on Tools
  griptape/mixins/activity_mixin.py
  tests/unit/mixins/test_activity_mixin.py
Labels: tools

#1745 feat(drivers-prompt-grok): add GrokPromptDriver
  .github/workflows/docs-integration-tests.yml
  docs/griptape-framework/drivers/prompt-drivers.md
  docs/griptape-framework/drivers/src/prompt_drivers_grok.py
  docs/griptape-framework/misc/src/tokenizers_grok.py
  docs/griptape-framework/misc/tokenizers.md
  griptape/drivers/__init__.py
  griptape/drivers/prompt/grok/__init__.py
  griptape/drivers/prompt/grok_prompt_driver.py
  griptape/tokenizers/__init__.py
  griptape/tokenizers/grok_tokenizer.py
  tests/unit/drivers/prompt/test_grok_prompt_driver.py
  tests/unit/tokenizers/test_grok_tokenizer.py
Labels: drivers

#1752 chore(release/1.3): release 1.3.5
  CHANGELOG.md
  pyproject.toml
Labels: autorelease: pending

#1692 feat(drivers): add GriptapeCloudPromptDriver
  docs/griptape-framework/drivers/prompt-drivers.md
  docs/griptape-framework/drivers/src/prompt_drivers_griptape_cloud.py
  griptape/drivers/__init__.py
  griptape/drivers/prompt/griptape_cloud/__init__.py
  griptape/drivers/prompt/griptape_cloud_prompt_driver.py
  tests/unit/drivers/prompt/test_griptape_cloud_prompt_driver.py
Labels: drivers

#1758 fix(drivers-event-listener-griptape-cloud): add type/timestamp fallbacks for custom events
  griptape/drivers/event_listener/griptape_cloud_event_listener_driver.py
  tests/unit/drivers/event_listener/test_griptape_cloud_event_listener_driver.py
Labels: events

#1761 chore(docs): resolve docs warnings
  docs/examples/talk-to-an-image.md
  docs/griptape-cloud/tools/run-tool.md
  docs/griptape-framework/drivers/rerank-drivers.md
  docs/griptape-framework/drivers/structure-run-drivers.md
  docs/griptape-framework/structures/task-memory.md
  docs/griptape-framework/tools/official-tools/audio-transcription-tool.md
  docs/griptape-framework/tools/official-tools/calculator-tool.md
  docs/griptape-framework/tools/official-tools/computer-tool.md
  docs/griptape-framework/tools/official-tools/date-time-tool.md
  docs/griptape-framework/tools/official-tools/email-tool.md
  docs/griptape-framework/tools/official-tools/extraction-tool.md
  docs/griptape-framework/tools/official-tools/file-manager-tool.md
  docs/griptape-framework/tools/official-tools/griptape-cloud-tool-tool.md
  docs/griptape-framework/tools/official-tools/image-query-tool.md
  docs/griptape-framework/tools/official-tools/inpainting-image-generation-tool.md
  docs/griptape-framework/tools/official-tools/outpainting-image-generation-tool.md
  docs/griptape-framework/tools/official-tools/prompt-image-generation-tool.md
  docs/griptape-framework/tools/official-tools/prompt-summary-tool.md
  docs/griptape-framework/tools/official-tools/query-tool.md
  docs/griptape-framework/tools/official-tools/rag-tool.md
  docs/griptape-framework/tools/official-tools/rest-api-tool.md
  docs/griptape-framework/tools/official-tools/sql-tool.md
  docs/griptape-framework/tools/official-tools/structure-run-tool.md
  docs/griptape-framework/tools/official-tools/text-to-speech-tool.md
  docs/griptape-framework/tools/official-tools/variation-image-generation-tool.md
  docs/griptape-framework/tools/official-tools/vector-store-tool.md
  docs/griptape-framework/tools/official-tools/web-scraper-tool.md
  docs/griptape-framework/tools/official-tools/web-search-tool.md
Labels: docs

#1772 feat(drivers-web-scraper-markdownify): update markdownify to 1.0.0
  griptape/drivers/web_scraper/markdownify_web_scraper_driver.py
  pyproject.toml
  uv.lock
Labels: drivers

#1775 chore(release/1.4): release 1.4.1
  CHANGELOG.md
  pyproject.toml
Labels: autorelease: pending

#1777 ci(docs): remove todo causing logs to regenerate
  .github/scripts/gen_snippet_logs.py
Labels: docs

#1783 chore(release/1.4): release 1.4.2
  CHANGELOG.md
  pyproject.toml
Labels: autorelease: pending
