Repository griptape-ai/griptape, pull requests merged in 2025-01, with the labels that each got.

#1443 Add Structured Output
  CHANGELOG.md
  docs/griptape-framework/drivers/prompt-drivers.md
  docs/griptape-framework/drivers/src/prompt_drivers_3.py
  docs/griptape-framework/drivers/src/prompt_drivers_structured_output.py
  docs/griptape-framework/structures/rulesets.md
  griptape/common/prompt_stack/prompt_stack.py
  griptape/drivers/prompt/amazon_bedrock_prompt_driver.py
  griptape/drivers/prompt/amazon_sagemaker_jumpstart_prompt_driver.py
  griptape/drivers/prompt/anthropic_prompt_driver.py
  griptape/drivers/prompt/base_prompt_driver.py
  griptape/drivers/prompt/cohere_prompt_driver.py
  griptape/drivers/prompt/google_prompt_driver.py
  griptape/drivers/prompt/huggingface_hub_prompt_driver.py
  griptape/drivers/prompt/huggingface_pipeline_prompt_driver.py
  griptape/drivers/prompt/ollama_prompt_driver.py
  griptape/drivers/prompt/openai_chat_prompt_driver.py
  griptape/schemas/base_schema.py
  griptape/structures/agent.py
  griptape/tasks/actions_subtask.py
  griptape/tasks/prompt_task.py
  griptape/tools/__init__.py
  griptape/tools/structured_output/__init__.py
  griptape/tools/structured_output/tool.py
  mise.toml
  pyproject.toml
  tests/mocks/mock_prompt_driver.py
  tests/unit/configs/drivers/test_amazon_bedrock_drivers_config.py
  tests/unit/configs/drivers/test_anthropic_drivers_config.py
  tests/unit/configs/drivers/test_azure_openai_drivers_config.py
  tests/unit/configs/drivers/test_cohere_drivers_config.py
  tests/unit/configs/drivers/test_drivers_config.py
  tests/unit/configs/drivers/test_google_drivers_config.py
  tests/unit/configs/drivers/test_openai_driver_config.py
  tests/unit/drivers/prompt/test_amazon_bedrock_prompt_driver.py
  tests/unit/drivers/prompt/test_amazon_sagemaker_jumpstart_prompt_driver.py
  tests/unit/drivers/prompt/test_anthropic_prompt_driver.py
  tests/unit/drivers/prompt/test_azure_openai_chat_prompt_driver.py
  tests/unit/drivers/prompt/test_base_prompt_driver.py
  tests/unit/drivers/prompt/test_cohere_prompt_driver.py
  tests/unit/drivers/prompt/test_google_prompt_driver.py
  tests/unit/drivers/prompt/test_hugging_face_hub_prompt_driver.py
  tests/unit/drivers/prompt/test_hugging_face_pipeline_prompt_driver.py
  tests/unit/drivers/prompt/test_ollama_prompt_driver.py
  tests/unit/drivers/prompt/test_openai_chat_prompt_driver.py
  tests/unit/structures/test_agent.py
  tests/unit/structures/test_structure.py
  tests/unit/tasks/test_actions_subtask.py
  tests/unit/tasks/test_prompt_task.py
  tests/unit/tasks/test_tool_task.py
  tests/unit/tasks/test_toolkit_task.py
  tests/unit/tools/test_structured_output_tool.py
Labels: type: feature request

#1383 Cloud Tool docs
  docs/griptape-cloud/index.md
  docs/griptape-cloud/structures/structure-config.md
  docs/griptape-cloud/tools/create-tool.md
  docs/griptape-cloud/tools/run-tool.md
  docs/griptape-cloud/tools/tool-config.md
  mkdocs.yml
Labels: type:documentation

#1582 Automatically create Thread in Griptape Cloud Assistant Driver
  CHANGELOG.md
  griptape/drivers/assistant/griptape_cloud_assistant_driver.py
  griptape/drivers/assistant/openai_assistant_driver.py
  tests/unit/drivers/assistant/test_griptape_cloud_assistant_driver.py
  tests/unit/drivers/assistant/test_openai_assistant_driver.py
Labels: type:enhancement
